word_pairs = [
    ('lift', 'elevator'),
    ('strawberry', 'cherry'),
    ('singapore', 'hongkong'),
    ('hobbit', 'lord of the rings'),
    ('ocean', 'sea'),
    ('lion', 'tiger'),
    ('apple', 'pear'),
    ('guitar', 'ukulele'),
    ('butterfly', 'moth'),
    ('volleyball', 'basketball'),
    ('sunflower', 'daisy'),
    ('piano', 'keyboard'),
    ('car', 'automobile'),
    ('mansion', 'villa'),
    ('castle', 'palace'),
    ('soup', 'stew'),
    ('lake', 'pond'),
    ('river', 'stream'),
    ('mountain', 'hill'),
    ('cloud', 'fog'),
    ('star', 'planet'),
    ('comet', 'asteroid'),
    ('snow', 'ice'),
    ('rain', 'drizzle'),
    ('wind', 'breeze'),
    ('storm', 'hurricane'),
    ('forest', 'jungle'),
    ('desert', 'oasis'),
    ('city', 'metropolis'),
    ('village', 'town'),
    # ...continue adding more pairs until you reach 100
]